<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Kindling.Sim</RootNamespace>
    <AssemblyName>Kindling.Sim</AssemblyName>
  </PropertyGroup>
</Project>
