. "$PSScriptRoot\_common.ps1"

Write-Host "Dream Gate Supabase setup"
Write-Host "========================="
Write-Host ""
Write-Host "1. Create a project at https://supabase.com/dashboard"
Write-Host "2. Open API settings and copy URL + keys"
Write-Host "3. Run: .\scripts\configure-backend.ps1"
Write-Host "4. In a normal PowerShell window (not automated):"
Write-Host "     `$env:PATH = `".\tools;`$env:PATH`""
Write-Host "     supabase login"
Write-Host "5. Then: .\scripts\complete-cloud-setup.ps1 -SkipLink (if already linked) ..."
Write-Host ""
Write-Host "Or set a personal access token from https://supabase.com/dashboard/account/tokens"
Write-Host "  `$env:SUPABASE_ACCESS_TOKEN = 'your-token'"
Write-Host ""

Start-Process "https://supabase.com/dashboard/projects"
Start-Process "https://supabase.com/dashboard/account/tokens"